pull_request_rules:
  - name: remove outdated reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews: {}

  - name: Automatic merge when all checks pass and the PR is approved
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=build"
      - "status-success=DCO"
      - "status-success=WIP"
      - "-draft"
    actions:
      merge:
        method: squash
        commit_message: title+body
        bot_account: jaegerci-bot